project:
  type: manuscript

manuscript:
  article: index.qmd

format:
  html:
    toc: true
    theme: cosmo
    number-sections: true
    page-footer:
      left: "Made with ❤️ using Quarto"
      right: "[View on GitHub](https://github.com/jc3482/fifa-ml-analysis)"
    sidebar:
      style: "floating"
      tools:
        - icon: github
          href: https://github.com/jc3482/fifa-ml-analysis
          text: "GitHub Repo"
